Explicitly check that pageContents is not an empty string.
langchain-ai/langchainjs pull request #2836
Opened 2023-10-08 08:08 UTC by skarard

This PR is related to a discussion in #2807, the current behaviour of the Document constructor `field.pageContent` when given an empty string is to set `pageContent` as `undefined`. This broke `HNSWLib.addDocuments()` as it attempts a string.replace() on `undefined` rather than the typed string `pageContents`.

I suggested allowing `pageContents` to be set as an empty string. @jacoblee93 suggested that a Document with an empty `pageContents` should not be created at all.

This implementation requires `pageContents` to be a string that is not empty, otherwise it throws `Error("pageContents must not be empty")`.

2023-10-09 17:41 UTC, jacoblee93 commented
Ideally we shouldn't need this with TypeScript, but an empty string should be permissible, just not a hard `undefined`, `null`, or non-string value - can you change?

2023-10-09 17:59 UTC, skarard commented
Sure I change this out to allow it to record an empty string.

On Mon, 9 Oct 2023, 18:41 Jacob Lee, ***@***.***> wrote:

> Ideally we shouldn't need this with TypeScript, but an empty string should
> be permissible, just not a hard undefined, null, or non-string value -
> can you change?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/langchain-ai/langchainjs/pull/2836#issuecomment-1753408078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAES7ZPDXG2I724JOIJLWXLX6QZMBAVCNFSM6AAAAAA5XQOJCWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJTGQYDQMBXHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-26 19:51 UTC, skarard commented
@jacoblee93 I added the proposed change and threw in a couple of unit tests for good measure.

2023-12-06 19:55 UTC, bracesproul requested changes
Hey @skarard sorry for taking so long to review, these changes look good! We've moved `document.ts` into `langchain-core/src/documents/document.ts`, could you push up a change moving your changes into that updated file then re-request my review?

Thanks again!

2025-04-28 08:46 UTC, benjamincburns commented on langchain-core/src/documents/tests/document.test.ts
> +import { Document } from "../document.js";
```suggestion
import { Document } from "../document.js";
import { describe, expect, test} from "@jest/globals";
```

2025-04-28 08:46 UTC, benjamincburns commented on langchain-core/src/documents/tests/document.test.ts
> +import { describe, expect, test} from "@jest/globals";
```suggestion
import { describe, expect, test } from "@jest/globals";
```

2025-04-28 11:19 UTC, benjamincburns commented
Thanks for the contribution!

2025-04-28 11:19 UTC, benjamincburns approved these changes

2025-04-28 11:38 UTC, merged