feat: FewShotChatMessagePromptTemplate
langchain-ai/langchainjs pull request #3053
Opened 2023-10-26 00:45 UTC by bracesproul

2023-10-27 17:37 UTC, bracesproul commented on langchain/src/prompts/few_shot.ts
> +  exampleSelector?: BaseExampleSelector | undefined;
```suggestion
  exampleSelector?: BaseExampleSelector;
```

2023-10-27 17:39 UTC, bracesproul commented on langchain/src/prompts/few_shot.ts
> +    /** @TODO - broken, what da hell 🫠 */
```suggestion
```

2023-10-27 17:39 UTC, bracesproul commented on langchain/src/prompts/few_shot.ts
> +  suffix?: string;
```suggestion
   * A prompt template string to put after the examples.
   *
   * @defaultValue `""`
   */
  suffix?: string;
```

2023-10-27 17:40 UTC, bracesproul commented on langchain/src/prompts/few_shot.ts
> +  templateFormat?: TemplateFormat;
```suggestion
   * The format of the prompt template. Options are: 'f-string'
   *
   * @defaultValue `f-string`
   */
  templateFormat?: TemplateFormat;
```

2023-10-27 17:40 UTC, bracesproul commented on langchain/src/prompts/few_shot.ts
> +  exampleSeparator?: string;
```suggestion
   * String separator used to join the prefix, the examples, and suffix.
   *
   * @defaultValue `"\n\n"`
   */
  exampleSeparator?: string;
```

2023-10-27 17:41 UTC, bracesproul commented on langchain/src/prompts/few_shot.ts
> +  validateTemplate?: boolean;
```suggestion
   * Whether or not to try validating the template on initialization.
   *
   * @defaultValue `true`
   */
  validateTemplate?: boolean;
```

2023-10-27 17:43 UTC, bracesproul reviewed
.

2023-10-28 15:23 UTC, jacoblee93 commented on langchain/src/prompts/few_shot.ts
> +    Object.assign(this, fields);
Do this explicitly, otherwise people can do dangerous things like override instance methods

2023-10-28 15:29 UTC, jacoblee93 requested changes

2023-10-28 15:29 UTC, jacoblee93 commented on langchain/src/prompts/tests/few_shot.test.ts
> +describe("FewShotChatMessagePromptTemplate", () => {
The most interesting thing to test here is `formatChatMessages`/`invoke`, which should return something like a list of chat messages I believe?

2023-10-28 15:29 UTC, jacoblee93 commented on langchain/src/prompts/few_shot.ts
> +{
Don't forget `static get lc_name`!

2023-10-31 18:18 UTC, jacoblee93 approved these changes

2023-10-31 18:18 UTC, merged

2023-10-31 18:23 UTC, bracesproul commented
> 

Yes, tracking here https://github.com/langchain-ai/langchainjs/issues/3110