Added PyInterpreterTool
langchain-ai/langchainjs pull request #3090
Opened 2023-10-29 18:55 UTC by mishushakov

2023-10-30 19:21 UTC, jacoblee93 requested changes
Very cool, needs docs as well. Can you also add a security warning to those as well?

2023-10-30 19:21 UTC, jacoblee93 commented on langchain/scripts/create-entrypoints.js
> +  "tools/pyinterpreter",
Let's move to `experimental` since it's potentially running arbitrary code

2023-10-30 19:21 UTC, jacoblee93 commented on langchain/scripts/create-entrypoints.js
> +  "tools/pyinterpreter",
You'll also need to add an entrypoint above

2023-10-30 19:21 UTC, jacoblee93 commented on langchain/package.json
> +    "pyodide": "0.24.1",
Add under `peerDependenciesMeta` below

2023-10-30 19:21 UTC, jacoblee93 commented on langchain/src/tools/index.ts
> +export { PythonInterpreterTool } from "./pyinterpreter.js";
We can't export from here if it requires an optional peer dep, we'll need to use a custom entrypoint

2023-10-30 23:36 UTC, mishushakov commented
Of course. Where should I put them? In the comments or do you have a special place for tools anywhere? 😄

What should the warning say? The code is executed in secure WASM sandbox...

I also have a question regarding the tests. Should it only test the tool itself or the complete chain like I did there?

Thanks

2023-10-31 00:44 UTC, jacoblee93 commented
> Of course. Where should I put them? In the comments or do you have a special place for tools anywhere? 😄
> 
> What should the warning say? The code is executed in secure WASM sandbox...
> 
> I also have a question regarding the tests. Should it only test the tool itself or the complete chain like I did there?
> 
> Thanks

Best place would be to add a new folder called `tools/experimental` and put it there.

2023-11-05 17:40 UTC, mishushakov commented
Ok done. Let me know where I should put the docs and the warning

2023-11-10 01:41 UTC, jacoblee93 commented
Hi so sorry, it's been a crazy week for us - will look at this and write docs tomorrow!

2023-11-13 18:42 UTC, jacoblee93 commented
Hey @mishushakov, I moved things around but the integration test seems rather flaky - do you think you could come up with a more consistent one?

2023-11-15 21:28 UTC, mishushakov commented
Hey, I have been busy this week, but happy to tackle this on the weekend!

2023-11-21 21:08 UTC, mishushakov commented
Is this better? Or are you looking for something else entirely?

```
import { test, expect } from "@jest/globals";
import { StringOutputParser } from "../../../schema/output_parser.js";
import { OpenAI } from "../../../llms/openai.js";
import { PromptTemplate } from "../../../prompts/index.js";
import { PythonInterpreterTool } from "../pyinterpreter.js";

describe("Python Interpreter testsuite", () => {
  test("hello langchain", async () => {
    const prompt = PromptTemplate.fromTemplate(
      `Can you generate python code that: {input}?`
    );

    const model = new OpenAI({});

    const interpreter = await PythonInterpreterTool.initialize({
      indexURL: "../node_modules/pyodide",
    });
    const chain = prompt
      .pipe(model)
      .pipe(new StringOutputParser())
      .pipe(interpreter);

    const result = await chain.invoke({
      input: `prints "Hello LangChain"`,
    });

    expect(JSON.parse(result).stdout).toBe("Hello LangChain");
  });
});
```

2023-11-21 21:10 UTC, mishushakov commented
The test does require OpenAI API key though

2023-11-21 21:17 UTC, mishushakov commented
Otherwise, a very basic test, that only tests the tool itself would look like:

```ts
import { test, expect } from "@jest/globals";
import { PythonInterpreterTool } from "../pyinterpreter.js";

describe("Python Interpreter testsuite", () => {
  test("hello langchain", async () => {
    const interpreter = await PythonInterpreterTool.initialize({
      indexURL: "../node_modules/pyodide",
    });

    const result = await interpreter._call(`print("Hello LangChain")`)
    expect(JSON.parse(result).stdout).toBe("Hello LangChain");
  });
});
```

2023-11-27 19:03 UTC, jacoblee93 approved these changes

2023-11-28 01:34 UTC, merged

2023-11-28 01:34 UTC, jacoblee93 commented
Thank you! It's really neat