Added script to generate compatibility tables for llm/chat models
langchain-ai/langchainjs pull request #3148
Opened 2023-11-03 20:09 UTC by bracesproul

2023-11-03 22:35 UTC, bracesproul commented on langchain/package.json
> +    "glob": "^10.3.10",
added as dev dep

2023-11-07 23:54 UTC, jacoblee93 commented on langchain/package.json
> +    "build:scripts": "node scripts/create-entrypoints.js && node scripts/check-tree-shaking.js && node scripts/model-docs-table.js",
Change to `generate-docs-llm-compatibility-table.js`

2023-11-07 23:54 UTC, jacoblee93 requested changes
LGTM, one naming nit

2023-11-08 02:06 UTC, jacoblee93 approved these changes

2023-11-08 02:07 UTC, merged