Rename LLMonitor Callback Handler
langchain-ai/langchainjs pull request #3667
Opened 2023-12-14 21:17 UTC by hughcrt

(Following #3614)

Hi,
We are renaming our product from LLMonitor to Lunary.ai.
This PR add the Lunary Callback Handler, but keeps the llmonitor one in order to avoid breaking changes.
Thanks!

2023-12-15 00:10 UTC, jacoblee93 commented on libs/langchain-google-genai/package.json
> -  "version": "0.0.3",
Looks like this got pulled in by accident?

2023-12-15 00:11 UTC, jacoblee93 commented on langchain/scripts/create-entrypoints.js
> +  "callbacks/handlers/lunary",
We've deprecated new integration exports from `langchain` - can you remove and change examples to import from `@langchain/community/callbacks/handlers/lunary`?

2023-12-15 00:11 UTC, jacoblee93 commented on langchain/callbacks/lunary.cjs
> +module.exports = require("../dist/callbacks/handlers/lunary.cjs");
These build artifacts should not be checked in, can you remove?

2023-12-15 00:12 UTC, jacoblee93 requested changes
Thanks! See comments, lots of structural changes recently:

2023-12-15 12:17 UTC, hughcrt commented
Hi @jacoblee93,
Thanks for your prompt answer. I've updated the code by following your instructions.

2023-12-15 17:08 UTC, hughcrt reviewed
Done

2023-12-19 09:12 UTC, hughcrt commented
Hi @jacoblee93 ,
Could you please check and confirm if the pull request can now be merged?

2023-12-22 00:04 UTC, bracesproul reviewed
looking good so far! I left a few comments, if you could resolve & re-request my review that would be great! Thank you!

2023-12-23 21:29 UTC, hughcrt commented
Hi @jacoblee93 ,

I have made the requested changes. Thanks

2024-01-02 18:19 UTC, bracesproul requested changes
Two small comments, also run `yarn format` from root then it's good to merge!

2024-01-02 18:19 UTC, bracesproul commented on docs/core_docs/docs/ecosystem/integrations/lunary.mdx
> +```bash
```suggestion
```bash npm2yarn
```

2024-01-02 18:19 UTC, bracesproul commented on langchain/callbacks/handlers/lunary.cjs
Please delete these three files in `langchain/callbacks/handlers`

2024-01-02 20:41 UTC, hughcrt commented
Hi @bracesproul,
Thanks for your review! I have deleted the build files, and ran `yarn format`

2024-01-04 00:28 UTC, jacoblee93 commented on libs/langchain-community/src/callbacks/handlers/lunary.ts
> +export { LunaryHandler } from "lunary/langchain";
This is fine but just keep in mind we won't be able to update if refactors happen

2024-01-04 00:33 UTC, jacoblee93 commented
Hey @hughcrt, couldn't push changes to your branch but have opened #3895 and will merge that tonight.

Thanks for your patience, apologies for the delays!

2024-01-04 01:00 UTC, closed without merging

2024-01-04 02:18 UTC, jacoblee93 commented
This is live in the latest @langchain/community