Adds experimental custom format prompt templates and handlebars
langchain-ai/langchainjs pull request #3885
Opened 2024-01-03 16:59 UTC by jacoblee93

@davidfant this would be the more isolated way of adding custom formats - we've had a lot of issues with jinja2 on Python and want to keep dependencies light anyway.

Let me know what you think and if this fits your use-case - we'd need to add chat prompt template variants as well but could start with something like this.

2024-01-03 23:09 UTC, davidfant commented on langchain/src/experimental/prompts/handlebars.ts
> +    params: Omit<
Should omit `renderer` too, and could be defaulted to an empty object so that it doesn't need to be provided

2024-01-03 23:40 UTC, davidfant commented on langchain/src/experimental/prompts/handlebars.ts
> +      renderer: interpolateHandlebars,
We should set `validateTemplate: false` here. Validating the handlebars templates with the f-string code doesn't make sense and throws errors:

```
Error: Invalid prompt schema: Single '}' in template.
    at checkValidTemplate (/Users/fant/repos/ai/langchainjs/langchain-core/dist/prompts/template.cjs:88:15)
    at new PromptTemplate (/Users/fant/repos/ai/langchainjs/langchain-core/dist/prompts/prompt.cjs:53:50)
    at new CustomFormatPromptTemplate (/Users/fant/repos/ai/langchainjs/langchain/dist/experimental/prompts/custom_format.cjs:10:9)
    at new HandlebarsPromptTemplate (/Users/fant/repos/ai/langchainjs/langchain/dist/experimental/prompts/handlebars.cjs:60:9)
    at Function.fromTemplate (/Users/fant/repos/ai/langchainjs/langchain/dist/experimental/prompts/custom_format.cjs:49:16)
    at Function.fromTemplate (/Users/fant/repos/ai/langchainjs/langchain/dist/experimental/prompts/handlebars.cjs:80:22)
    at Object.<anonymous> (/Users/fant/repos/ai/godmode/packages/hydra/src/runnables/agent/planTool/default/prompt.ts:76:30)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (/Users/fant/repos/ai/godmode/packages/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/j2/stdvm9c50l109dgfdqv45x400000gn/T/ts-node-dev-hook-25024792164166465.js:69:33)
```

2024-01-08 10:04 UTC, davidfant requested changes

2024-01-08 10:04 UTC, davidfant commented on langchain/src/experimental/prompts/handlebars.ts
> +      nodes.push([...node.params, ...node.program.body]);
```suggestion
      nodes.push(...node.params, ...node.program.body);
```

2024-01-09 19:20 UTC, jacoblee93 commented
Requires a new `@langchain/core` release and version bump.

2024-01-09 22:22 UTC, merged

2024-01-09 22:22 UTC, jacoblee93 commented
Thank you for your patience @davidfant!