community[minor]: Add support for Azure AI Search vector store
langchain-ai/langchainjs pull request #4044
Opened 2024-01-16 20:12 UTC by sinedied

This PR add Azure AI Search vectore store integration.
This is a follow-up of https://github.com/langchain-ai/langchainjs/pull/2396 that has been stuck for months. I forked the original PR to keep the prior contribution history, I hope it's ok that way.

Many changes happened since the original PR, as Azure Cognitive Search was renamed Azure AI Search,the SDK was updated with breaking changes, and LangChainJS structure has also changed.
I updated all of these, and went a bit further to align with the existing Azure Cosmos DB integration documentation, examples and tests.

> Note: this is an initial version to unblock the usage of this service, but I plan to push it a bit further in another PR with options to customize the index schema and fit existing indexes.

Fixes #2349 
Twitter: @sinedied

2024-01-18 01:58 UTC, pablocastro requested changes
Thanks for adding Azure AI Search support! I left a number of comments in the PR, happy to clarify anything in the comments.

2024-01-18 10:40 UTC, sinedied commented on docs/api_refs/typedoc.json
> +    "../../libs/langchain-cloudflare/src/index.ts",
Not really, this file auto-generated when building Langchain so it was probably missed in a previous PR

2024-01-18 10:41 UTC, sinedied commented on docs/api_refs/typedoc.json
> +    "../../langchain-core/src/utils/function_calling.ts",
Same as above, this file is generated automatically

2024-01-18 10:45 UTC, sinedied commented on langchain/package.json
> +    "@aws-sdk/signature-v4": "^3.374.0",
Good catch, this comes from the previous PR and I missed that one in the cleanup

2024-01-18 10:49 UTC, sinedied commented on libs/langchain-community/src/vectorstores/azure_aisearch.ts
> +    if (!config.client && !endpoint && !key) {
Thanks, fixed

2024-01-18 10:52 UTC, sinedied commented on libs/langchain-community/src/vectorstores/azure_aisearch.ts
> +          embedding: item.document[DEFAULT_FIELD_CONTENT_VECTOR],
It's needed to implement the `maxMarginalRelevanceSearch()` method.
In the next PR I can however add an option to include it (like some other LC integrations) and make it disabled by default

2024-01-18 10:55 UTC, sinedied commented on libs/langchain-community/src/vectorstores/azure_aisearch.ts
> +          vectorSearchDimensions: 1536,
Good catch. I'll check if we can get it from the LC embedding model directly or add it to the config

2024-01-18 10:59 UTC, sinedied commented on libs/langchain-community/src/vectorstores/azure_aisearch.ts
> +          type: "Edm.ComplexType",
Yes, I'm not quite happy with that one and it comes from the base implementation I started from. 
But I thought as a default as least it makes it easier for the users who do not want to bother with the schema, as LC allows for arbitrary metadata.

That's also why I said I wand to provide more customizations options in another PR to allow for custom index schema for the users who wants better control over the data and filters.

2024-01-18 10:59 UTC, sinedied commented on yarn.lock
> +    "@aws-sdk/signature-v4": ^3.374.0
Yes, cleaned

2024-01-18 11:11 UTC, sinedied commented on libs/langchain-community/src/vectorstores/azure_aisearch.ts
> +        captions: {
Currently it's not, so I'm removing it. We might always add it later as an option

2024-01-18 14:03 UTC, sinedied commented on docs/api_refs/typedoc.json
> +    "../../libs/langchain-cloudflare/src/index.ts",
Solved after a rebase from main

2024-01-18 14:03 UTC, sinedied commented on docs/api_refs/typedoc.json
> +    "../../langchain-core/src/utils/function_calling.ts",
Solved after a rebase from main

2024-01-19 10:16 UTC, sinedied commented
Thanks for the feedbacks! I'm leaving some of the comment open here for reference, as I'd like to tackle these in a separate PR (optional embeddings, improved schema and maybe think of the 100k limit).

It seems there's a still build issue coming from the main branch, but otherwise the PR is ready for the next step.

2024-01-19 17:10 UTC, pablocastro approved these changes
LGTM 

(I think it's fine to defer > 100K docs operations and the metadata structure topic, this is already useful in most scenarios without either of those)

2024-01-19 17:14 UTC, farzad528 approved these changes

2024-01-24 14:46 UTC, sinedied commented
Thanks @jacoblee93 for your review and comments, I'll update the PR in the coming days and rebase it from main to fix the conflict

2024-01-24 17:20 UTC, sinedied commented on libs/langchain-community/src/vectorstores/azure_aisearch.ts
> +  async deleteMany(filter: string): Promise<IndexingResult[]> {
Thanks, fixed

2024-01-25 08:37 UTC, sinedied commented on libs/langchain-community/src/vectorstores/azure_aisearch.ts
> +      const batchEmbeddings: number[][] = await this.embeddings.embedDocuments(
Fixed

2024-01-25 08:39 UTC, sinedied commented on libs/langchain-community/src/vectorstores/azure_aisearch.ts
> +          embedding: item.document[DEFAULT_FIELD_CONTENT_VECTOR],
I made it disabled by default, and added the property in the metadata type to surface it clearly, so the prefix should not be needed now

2024-01-25 08:54 UTC, sinedied commented
@jacoblee93 I've process all comments an rebased the branch

2024-01-26 20:17 UTC, jacoblee93 commented
Looks good - unfortunate about metadata filtering but I think better to get it in at this point.

2024-01-27 00:31 UTC, jacoblee93 commented
Thank you!

2024-01-27 00:52 UTC, merged