types: the args of `where` is optional in  `WeaviateFilter`
langchain-ai/langchainjs pull request #5193
Opened 2024-04-24 04:10 UTC by hehuangz

Fixes # (issue)

it's not necessary pass distance and where condition at the same time

2024-04-24 20:29 UTC, jacoblee93 commented
Thank you!

2024-04-24 20:40 UTC, jacoblee93 commented
Seems it's failing build - can you have a look?

2024-04-25 03:18 UTC, hehuangz commented
> Seems it's failing build - can you have a look?

ok

2024-04-25 08:29 UTC, hehuangz commented
> Seems it's failing build - can you have a look?

Hi, I don't have a better way to revise it, please check if it works, thanks!

2024-04-26 18:18 UTC, bracesproul requested changes
Dismiss this

2024-04-26 18:18 UTC, bracesproul commented on libs/langchain-community/src/vectorstores/weaviate.ts
> +  where?: WhereFilter;
This will be a breaking change to anyone using this and not already passing `where`

2024-04-26 22:41 UTC, jacoblee93 commented
Getting:
```
Error: @langchain/weaviate:build: src/vectorstores.ts(243,20): error TS2345: Argument of type '{ operands?: ...[] | undefined; operator?: "And" | "Or" | "Equal" | "Like" | "NotEqual" | "GreaterThan" | "GreaterThanEqual" | "LessThan" | "LessThanEqual" | "WithinGeoRange" | "IsNull" | "ContainsAny" | "ContainsAll" | undefined; ... 13 more ...; valueGeoRange?: { ...; } | undefined; } | undefined' is not assignable to parameter of type '{ operands?: ...[] | undefined; operator?: "And" | "Or" | "Equal" | "Like" | "NotEqual" | "GreaterThan" | "GreaterThanEqual" | "LessThan" | "LessThanEqual" | "WithinGeoRange" | "IsNull" | "ContainsAny" | "ContainsAll" | undefined; ... 13 more ...; valueGeoRange?: { ...; } | undefined; }'.
```

On CI build

2024-08-28 18:31 UTC, bracesproul commented
Closing due to CI issues. Please open a new PR with the CI issues fixed if you'd still like to get this merged. Thank you!

2024-08-28 18:31 UTC, closed without merging