lanchain-community [feature]: DeepInfra embeddings integration #1
langchain-ai/langchainjs pull request #5382
Opened 2024-05-15 10:38 UTC by ovuruska

**Description**

Implemented a new embedding integration that makes https://github.com/deepinfra's embedding models available on langchainjs. A new class named DeepInfraEmbeddings is created, which wraps the inference API.

This PR includes an example and integration tests related to the newly implemented class. Apart from the new integration's configuration, the original open-source components are intentionally left unchanged to avoid introducing any breaking changes.

2024-05-20 20:19 UTC, jacoblee93 requested changes

2024-05-20 20:19 UTC, jacoblee93 commented on libs/langchain-community/src/embeddings/deepinfra.ts
> +import axios, {AxiosInstance, AxiosResponse} from "axios";
`axios` isn't a dependency - can you use plain `fetch` instead?

2024-05-20 20:19 UTC, jacoblee93 commented on libs/langchain-community/src/embeddings/deepinfra.ts
> +import axios, {AxiosInstance, AxiosResponse} from "axios";
Please also run `yarn format`

2024-05-20 20:19 UTC, jacoblee93 commented on libs/langchain-community/src/embeddings/deepinfra.ts
> +    const batches = chunkArray(inputs, this.batchSize) as string[][];
Cast shouldn't be necessary?

2024-05-20 20:19 UTC, jacoblee93 commented on libs/langchain-community/src/embeddings/deepinfra.ts
> +    const response = await this.caller.call(this.client.post.bind(this.client,""), request);
What is the second arg you're binding here?

2024-05-20 20:19 UTC, jacoblee93 commented on libs/langchain-community/src/embeddings/deepinfra.ts
> +  static async imports(): Promise<{}> {
Remove

2024-05-20 20:19 UTC, jacoblee93 commented
Thank you, sorry for the delay!

2024-05-22 05:53 UTC, ovuruska commented
@jacoblee93 Thanks for the feedback!

2024-05-25 22:43 UTC, jacoblee93 commented
Looks good, can you add a documentation page under `docs/core_docs/docs/integrations/text_embedding/` to accompany the examples though?

2024-05-28 11:28 UTC, ovuruska commented
Thanks @jacoblee93 , I updated the documentation.

2024-05-31 21:27 UTC, jacoblee93 approved these changes

2024-05-31 21:27 UTC, jacoblee93 commented
Thank you!

2024-05-31 22:53 UTC, merged