Added Search Functionality to FireCrawl Loader
langchain-ai/langchainjs pull request #5418
Opened 2024-05-16 18:42 UTC by rafaelsideguide

This PR adds search functionality to the FireCrawl document loader, enabling users to search and retrieve specific data from the web.

This enhancement builds on the original FireCrawl loader introduced in PR [#5180](https://github.com/langchain-ai/langchainjs/pull/5180).

Thank you!

2024-05-17 20:45 UTC, bracesproul requested changes
Thanks for pushing this up! I left a couple comments, and have one bigger request:
This search functionality should be a retriever, and not a document loader. Would you be willing to instead refactor this PR to not add any new functionality to the document loader, but instead create a new firecrawl retriever which has the ability to search?

You can use [this retriever](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-exa/src/retrievers.ts) for reference

2024-05-20 21:09 UTC, rafaelsideguide commented
> Thanks for pushing this up! I left a couple comments, and have one bigger request: This search functionality should be a retriever, and not a document loader. Would you be willing to instead refactor this PR to not add any new functionality to the document loader, but instead create a new firecrawl retriever which has the ability to search?
> 
> You can use [this retriever](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-exa/src/retrievers.ts) for reference

@bracesproul I just changed the search implementation following your suggestions!

2024-06-11 14:10 UTC, rafaelsideguide commented
Hey @bracesproul I've made the changes you asked for in the firecrawl retriever. Could you take a look when you get a chance? I want to make sure it's all good.

2024-08-28 18:35 UTC, bracesproul commented on langchain/src/document_loaders/web/firecrawl.ts
> +}
```suggestion
}

```

2024-09-17 15:22 UTC, closed without merging