[community]fix: #6296 add clientParams for chromadb.
langchain-ai/langchainjs pull request #6308
Opened 2024-08-01 08:36 UTC by jeasonnow

Fixes #6296

2024-08-01 21:06 UTC, bracesproul requested changes
One small comment, otherwise this looks good

2024-08-01 21:06 UTC, bracesproul commented on libs/langchain-community/src/vectorstores/chroma.ts
> +    args: ChromaLibArgs & { clientParams?: Omit<ChromaClientParams, "path"> }
Could you instead make this a single exported interface `ChromaArgs`

2024-08-01 21:06 UTC, bracesproul commented on libs/langchain-community/src/vectorstores/chroma.ts
> +    args: ChromaLibArgs & { clientParams?: Omit<ChromaClientParams, "path"> }
Actually, just update `ChromaLibArgs` to include this `clientParams` field in both options of the type. That should be enough

2024-08-02 00:01 UTC, jacoblee93 commented
Thanks for this!

@bracesproul before we ship a new community version with this can we make sure there's no peer dep conflicts from `npm install`?

2024-08-03 01:00 UTC, jacoblee93 commented
Thank you!

2024-08-03 01:18 UTC, merged