Added Pinecone Hybrid Search
langchain-ai/langchainjs pull request #659
Opened 2023-04-07 11:18 UTC by ElektrikSpark

I tried to emulate the langchain python implementation of Pinecone Hybrid Search. I also used the Supabase Hybrid Search implementation as a reference. Thanks @hwchase17 @ericciarla 

I went with `BertWordPieceTokenizer` from `tokenizers` as the tokenizer. I also had to update the `@pinecone-database/pinecone` to `^0.0.12` as I could not add `sparseVectors` otherwise.

Not 100% sure if everything is in working order yet, but I will work on testing it in my local project when I get the chance. A good starting point nonetheless!

2023-04-07 23:48 UTC, ElektrikSpark commented
I had an oversight with using the `tokenizers` library. It only supports `"node": ">=10 < 11 || >=12 <14"`. Will evaluate alternative methods to create the sparse vectors.

2023-04-09 03:02 UTC, ElektrikSpark commented
@nfcampos @hwchase17 I think this is ready to be reviewed whenever the chance. 

I am using `bert-tokenizer` as the tokenizer for now, but down the road we will want to support a greater variety of tokenizer options. I initially tried to implement `tokenizers` from Hugging Face, but the node bindings are too old.

2023-04-11 17:32 UTC, nfcampos commented
Note to me: use tiktoken instead of bert

2023-05-25 00:55 UTC, dqbd commented on examples/src/retrievers/pinecone_hybrid.ts
> +  const tokenizer = new BertTokenizer(undefined, true, 512);
Consider using `js-tiktoken` instead, which should match the behavior of `OpenAIEmbeddings`

2023-05-25 00:56 UTC, dqbd commented on langchain/src/retrievers/pinecone-hybrid-search.ts
> +    this.topK = args.topK;
_nit_: the default values are being overriden, should that be the case?


```suggestion
    this.topK = args.topK ?? 4;
```

2023-05-25 00:57 UTC, dqbd commented on langchain/src/retrievers/pinecone-hybrid-search.ts
> +    this.alpha = args.alpha;
_nit_: the default values are being overriden, should that be the case?

```suggestion
    this.topK = args.topK ?? 4;
    this.alpha = args.alpha ?? 0.5;
```

2023-05-25 01:16 UTC, dqbd requested changes

2023-05-25 01:16 UTC, dqbd commented on langchain/src/retrievers/index.ts
> +  PineconeHybridSearchRetriever,
Instead of adding a file into a barrel file, create a new entrypoint instead.

2023-05-25 01:16 UTC, dqbd commented on langchain/src/retrievers/pinecone-hybrid-search.ts
> +  tokenizer: BertTokenizer;
I think it would make more sense for the sparse encoder to be more configurable, not assuming BERT tokenization.

2023-05-25 01:16 UTC, dqbd commented on langchain/src/retrievers/pinecone-hybrid-search.ts
> +      throw new Error("Alpha must be between 0 and 1");
_nit_: consider validating `this.alpha` in the constructor. 

_nit_: do we need to pass `this.alpha` as a parameter? Why not access it directly?

2023-05-25 01:16 UTC, dqbd commented on langchain/src/retrievers/pinecone-hybrid-search.ts
> +      throw new Error("Alpha must be between 0 and 1");
_nit_: consider validating `this.alpha` in the constructor. 
_nit_: do we need to pass `this.alpha` as a parameter? Why not access it directly?

2024-08-28 18:49 UTC, bracesproul commented
@carlosdp going to close due to merge conflicts. If you'd still like to get this merged in, please open off of an up-to-date `main` branch, and I'll review. Thank you!

2024-08-28 18:49 UTC, closed without merging