add jigsawtack integration
langchain-ai/langchainjs pull request #6665
Opened 2024-08-30 19:34 UTC by iamNarcisse

2024-09-04 21:56 UTC, jacoblee93 requested changes
Thanks for the PR!

We'd need to write docs for this - but we've also been trying to move new partner integrations into separate repos to make management a bit easier. You could still add docs to the main `langchain` repo and they'd appear under:

https://js.langchain.com/v0.2/docs/integrations/platforms/

You could then manage your own releases as `@jigsawstack/langchain` or something similar, or could grant us access to the repo and we could push releases as `@langchain/jigsawstack`, whichever you prefer.

2024-09-04 21:56 UTC, jacoblee93 commented on deno.lock
Can you remove this?

2024-09-04 21:56 UTC, jacoblee93 commented on libs/langchain-jigsawstack/src/llms.ts
> +      api_key: "JIGSAWSTACK_API_KEY",
You don't need the snake cased version of this

2024-09-04 21:56 UTC, jacoblee93 commented on libs/langchain-jigsawstack/src/llms.ts
> +  get lc_aliases(): { [key: string]: string } | undefined {
You don't need this

2024-09-05 08:47 UTC, iamNarcisse commented on deno.lock
Sure will do

2024-09-05 08:47 UTC, iamNarcisse commented on libs/langchain-jigsawstack/src/llms.ts
> +  get lc_aliases(): { [key: string]: string } | undefined {
Alright.

2024-09-06 14:08 UTC, iamNarcisse commented
> Thanks for the PR!
> 
> We'd need to write docs for this - but we've also been trying to move new partner integrations into separate repos to make management a bit easier. You could still add docs to the main `langchain` repo and they'd appear under:
> 
> https://js.langchain.com/v0.2/docs/integrations/platforms/
> 
> You could then manage your own releases as `@jigsawstack/langchain` or something similar, or could grant us access to the repo and we could push releases as `@langchain/jigsawstack`, whichever you prefer.
> 
> We could also move these into `@langchain/community`.

Hi @jacoblee93, 

I have made the requested changes. Let me know if it's all good. 

On how releases would be deployed, We'd prefer releases  as `@langchain/jigsawstack`

2024-09-10 20:29 UTC, jacoblee93 commented
> On how releases would be deployed, We'd prefer releases as @langchain/jigsawstack. The docs have been prepared and will be included in a separate PR.

In that case, could you make a separate repo and add add me as an admin? I'll be able to cut releases from there.

2024-09-13 11:21 UTC, iamNarcisse commented
> > On how releases would be deployed, We'd prefer releases as @langchain/jigsawstack. The docs have been prepared and will be included in a separate PR.
> 
> In that case, could you make a separate repo and add add me as an admin? I'll be able to cut releases from there.

Alright

2024-09-13 21:35 UTC, iamNarcisse commented
@jacoblee93, made PR for the docs here  #6767

2024-09-20 18:25 UTC, bracesproul requested changes
@iamNarcisse if you want the code to be released as `@langchain/jigsawstack` you'll have to remove the `libs/langchain-jigsawstack` dir in this PR & create a separate repo (managed by you, but with admin perms granted to jacob/myself. Alternatively you can move the code into `libs/langchain-community`.

Please pig me when one of these has been done & I can take a look!

2024-09-20 21:50 UTC, iamNarcisse commented
> @iamNarcisse if you want the code to be released as `@langchain/jigsawstack` you'll have to remove the `libs/langchain-jigsawstack` dir in this PR & create a separate repo (managed by you, but with admin perms granted to jacob/myself. Alternatively you can move the code into `libs/langchain-community`.
> 
> Please pig me when one of these has been done & I can take a look!

Hi @bracesproul, thanks for the feedback. I have removed dir `libs/langchain-jigsawstack`  and made a separate PR for the docs, see #6767. I have added @jacoblee93 to the forked repo that contains the code.

2024-09-27 20:57 UTC, closed without merging