feat(langchain): Allow to passthrough model kwargs via createToolCallingAgent
langchain-ai/langchainjs pull request #6743
Opened 2024-09-12 06:31 UTC by OlegIvaniv

This PR adds optional `kwargs` parameter to `createToolCallingAgent` which are passed to `llm.bindTools`. This is useful when user needs to specify some model provider parameters, for example to always require the model to use a tool(`{ tool_choice: 'required' }`)

2024-09-12 16:16 UTC, bracesproul requested changes
left one small comment, other than that this looks good!
Once fixed please re-request my review

2024-09-12 16:16 UTC, bracesproul commented on langchain/src/agents/tool_calling/index.ts
> +  kwargs?: Record<string, unknown>;
Lets use the base interface, combined w/ `Record<string, any>` (not 100% sure if you need the `Partial<>`)
```suggestion
  kwargs?: BaseChatModelCallOptions & Partial<Record<string, any>>;
```

2024-09-12 17:41 UTC, OlegIvaniv commented
Thanks, @bracesproul! Can you have another look, please?

2024-09-17 08:06 UTC, OlegIvaniv commented
Ping @bracesproul :P

2024-09-18 21:15 UTC, jacoblee93 commented
Thanks for this @OlegIvaniv!

You should now be able to pass a `model.bindTools([...], { tool_choice: "required" })` directly into the factory method - would that be sufficient for your use case?

2024-09-24 12:50 UTC, OlegIvaniv commented
> Thanks for this @OlegIvaniv!
> 
> You should now be able to pass a `model.bindTools([...], { tool_choice: "required" })` directly into the factory method - would that be sufficient for your use case?

Hi, @jacoblee93. Yes, that would indeed solve it. Although the syntax feels a bit awkward now as you'd need to pass tools to both `model.bindTools`, then to `createToolCallingAgent`, and finally to `new AgentExecutor`, it's something I can live with. :D Thanks!

2024-09-24 12:50 UTC, closed without merging