Cohere client support
langchain-ai/langchainjs pull request #6938
Opened 2024-10-04 10:46 UTC by debkanchan

Adds support for directly using Cohere client through a `client` parameter enabling use of Cohere on Azure, Cohere on AWS Bedrock and Standalone Cohere instances

2024-10-07 16:31 UTC, bracesproul approved these changes
lgtm! Thanks for doing this

2024-10-07 16:50 UTC, bracesproul requested changes
looks like CI is failing. Could you push up fixes and re-request my review once done?

2024-10-07 16:51 UTC, debkanchan commented
Sure, will do tomorrow

2024-10-09 07:30 UTC, debkanchan commented on libs/langchain-cohere/src/rerank.ts
> +// }
Done

2024-10-11 20:26 UTC, bracesproul approved these changes
lgtm as long as CI passes

2024-10-13 23:15 UTC, jacoblee93 commented
Looks great thanks!

2024-10-13 23:57 UTC, merged