add session context for a user mongodb
langchain-ai/langchainjs pull request #7436
Opened 2024-12-27 08:39 UTC by crisjy

Fixes # (issue)

2025-01-02 19:19 UTC, jacoblee93 reviewed
Seems reasonable to me!

@sinedied do you mind giving this a look?

2025-01-03 10:10 UTC, sinedied requested changes
Thanks @crisjy !
The context handling looks fine here, but you're missing user handling, which is needed to list/delete sessions otherwise you have no distinction of users.

What we did in the other CosmosDB implementation is make `userId` parameter optional in the DB options and set it to `anonymous` by default to keep compatibility with other implementation (or when user handling is not needed).

2025-01-03 10:10 UTC, sinedied commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +      console.log("Error setting context", error);
Would be better to throw so these errors can be identified

2025-01-03 10:10 UTC, sinedied commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +      console.log("Error clearing sessions:", error);
Would be better to throw so these errors can be identified

2025-01-03 10:10 UTC, sinedied commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +      await this.collection.deleteMany({});
This would delete all sessions for all users, which might not be the intended behavior... I think you missed the user handling here

2025-01-10 21:51 UTC, jacoblee93 commented
@crisjy let me know when this is ready for another look!

2025-01-12 15:12 UTC, crisjy commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +      console.log("Error setting context", error);
throw errors for this

2025-01-12 15:12 UTC, crisjy commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +      await this.collection.deleteMany({});
yep, add user id as handle for sessions, thank you for your comment!

2025-01-12 15:13 UTC, crisjy commented
> @crisjy let me know when this is ready for another look!

@jacoblee93 @sinedied resolve comments for this pr, sorry for delay, could you help me to have a look? thank you!

2025-01-13 10:51 UTC, sinedied requested changes
Thanks, the update with userId support looks great!

Though you forgot to add the filter for the current userId on the getAllSessions() and clearAllSessions() methods, as it should apply only to the current users. Should be a quick fix :)

2025-01-13 10:51 UTC, sinedied commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +    const documents = await this.collection.find().toArray();
Missing user filter here

2025-01-13 10:51 UTC, sinedied commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +      await this.collection.deleteMany({});
I think you forgot to update this call to filter it for the current user only

2025-01-14 03:42 UTC, crisjy commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +      await this.collection.deleteMany({});
add user id as handler to clear sessions

2025-01-14 15:11 UTC, crisjy commented
@sinedied @jacoblee93  comments resolved, could you help me have another look? Thank you!

2025-01-14 16:47 UTC, sinedied approved these changes

2025-01-14 16:48 UTC, sinedied commented
LGTM, thanks!

2025-01-15 02:21 UTC, crisjy commented
@jacoblee93 Hi jacob, could you help me have another look at this PR, thanks!

2025-01-18 07:57 UTC, jacoblee93 commented on libs/langchain-azure-cosmosdb/src/chat_histories/mongodb.ts
> +        { [ID_KEY]: this.sessionId },
Do we need `[ID_USER]: this.userId,` here too?

I assume this is sufficient in this case to just pass id?

2025-01-18 07:57 UTC, jacoblee93 approved these changes
Thank you!

2025-01-18 08:14 UTC, merged